// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/AbhinavPalacharla/xtrn-personal/internal/db/models"
)

type McpServerImage struct {
	ID            string
	Slug          string
	Version       int64
	Name          string
	DockerImage   string
	Type          string
	OauthProvider sql.NullString
	EnvSchema     models.EnvSchema
}

type McpServerInstance struct {
	ID        string
	Slug      string
	Version   int64
	Address   string
	Env       interface{}
	CreatedAt sql.NullTime
}

type OauthProvider struct {
	Name         string
	ClientID     string
	ClientSecret string
	CallbackUrl  string
	Scopes       sql.NullString
}

type OauthToken struct {
	ID            string
	RefreshToken  string
	OauthProvider string
}
