// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/AbhinavPalacharla/xtrn-personal/internal/db/models"
)

type Chat struct {
	ID        string
	Title     sql.NullString
	CreatedAt sql.NullTime
}

type McpServerImage struct {
	ID            string
	Slug          string
	Version       int64
	Name          string
	DockerImage   string
	Type          string
	OauthProvider sql.NullString
	EnvSchema     models.EnvSchema
}

type McpServerInstance struct {
	ID        string
	Slug      string
	Version   int64
	Address   string
	Env       interface{}
	CreatedAt sql.NullTime
}

type Message struct {
	ID        string
	ChatID    string
	Role      models.MessageRole
	Type      models.MessageType
	Content   sql.NullString
	CreatedAt sql.NullTime
}

type OauthProvider struct {
	Name         string
	ClientID     string
	ClientSecret string
}

type OauthToken struct {
	ID            string
	AccessToken   string
	RefreshToken  string
	Expiry        string
	OauthProvider string
}

type ToolCallRe struct {
	MessageID interface{}
	ToolUseID string
	Content   string
	IsError   sql.NullBool
}

type ToolCallReq struct {
	MessageID interface{}
	ToolUseID string
	Name      string
	Arguments string
}
