// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/AbhinavPalacharla/xtrn-personal/internal/db/models"
	"github.com/AbhinavPalacharla/xtrn-personal/internal/db/models/query_types"
)

type AiMessagePart struct {
	ID        int64
	Type      sql.NullString
	PartIndex int64
	MessageID string
}

type Chat struct {
	ID string
}

type McpServerImage struct {
	ID            string
	Slug          string
	Version       int64
	Name          string
	DockerImage   string
	Type          string
	OauthProvider sql.NullString
	EnvSchema     models.EnvSchema
}

type McpServerInstance struct {
	ID        string
	Slug      string
	Version   int64
	Address   string
	Env       interface{}
	CreatedAt sql.NullTime
}

type McpServerTool struct {
	ID          string
	Name        string
	Description sql.NullString
	Schema      string
	ImageID     string
}

type Message struct {
	ID         string
	Role       string
	Content    sql.NullString
	StopReason sql.NullString
	ChatID     string
}

type OauthProvider struct {
	Name         string
	ClientID     string
	ClientSecret string
	CallbackUrl  string
	Scopes       sql.NullString
}

type OauthToken struct {
	ID            string
	RefreshToken  string
	OauthProvider string
}

type TextPart struct {
	ID            int64
	Text          sql.NullString
	MessagePartID string
}

type ToolCallPart struct {
	ID            int64
	ToolCallID    string
	Name          string
	Arguments     string
	MessagePartID string
}

type ToolCallResult struct {
	MessageID  string
	ToolCallID string
	Name       string
	Content    string
	IsError    bool
}

type VGetChatMessage struct {
	ID         string
	Role       string
	Content    sql.NullString
	StopReason sql.NullString
	ChatID     string
	AiMessage  query_types.AIParts
	ToolResult query_types.ToolResult
}
