// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAllMCPinstances(ctx context.Context) error
	DeleteMCPServerInstance(ctx context.Context, id string) error
	GetMCPServerImage(ctx context.Context, id string) (GetMCPServerImageRow, error)
	GetMCPServerInstances(ctx context.Context) ([]GetMCPServerInstancesRow, error)
	GetOauthTokenByProvider(ctx context.Context, oauthProvider string) (OauthToken, error)
	//*********************************
	InsertMCPServerImage(ctx context.Context, arg InsertMCPServerImageParams) error
	//*********************************
	InsertMCPServerInstance(ctx context.Context, arg InsertMCPServerInstanceParams) error
	InsertMCPServerInstanceTool(ctx context.Context, arg InsertMCPServerInstanceToolParams) error
	//*********************************
	InsertOauthProvider(ctx context.Context, arg InsertOauthProviderParams) error
	InsertOauthToken(ctx context.Context, arg InsertOauthTokenParams) error
	UpdateOauthTokenByProivder(ctx context.Context, arg UpdateOauthTokenByProivderParams) error
}

var _ Querier = (*Queries)(nil)
