// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAllMCPinstances(ctx context.Context) error
	DeleteMCPServerInstance(ctx context.Context, id string) error
	GetChatWithAuthAndMessages(ctx context.Context, chatID string) (VGetChatWithAuthAndMessage, error)
	GetMCPServerImage(ctx context.Context, id string) (GetMCPServerImageRow, error)
	GetMCPServerInstances(ctx context.Context) ([]GetMCPServerInstancesRow, error)
	//*********************************
	GetOauthInstancesWithTools(ctx context.Context) ([]VGetOauthInstancesWithTool, error)
	GetOauthTokenByProvider(ctx context.Context, oauthProvider string) (OauthToken, error)
	//*********************************
	GetViewChatMessges(ctx context.Context, chatID string) ([]VGetChatMessage, error)
	InsertAIMessagePart(ctx context.Context, arg InsertAIMessagePartParams) (int64, error)
	InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error
	//*********************************
	InsertChat(ctx context.Context, id string) error
	//*********************************
	InsertMCPServerImage(ctx context.Context, arg InsertMCPServerImageParams) error
	//*********************************
	InsertMCPServerInstance(ctx context.Context, arg InsertMCPServerInstanceParams) error
	InsertMCPServerInstanceTool(ctx context.Context, arg InsertMCPServerInstanceToolParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	//*********************************
	InsertOauthProvider(ctx context.Context, arg InsertOauthProviderParams) error
	InsertOauthToken(ctx context.Context, arg InsertOauthTokenParams) error
	InsertTextPart(ctx context.Context, arg InsertTextPartParams) error
	InsertToolCallPart(ctx context.Context, arg InsertToolCallPartParams) error
	InsertToolCallResult(ctx context.Context, arg InsertToolCallResultParams) error
	UpdateOauthTokenByProivder(ctx context.Context, arg UpdateOauthTokenByProivderParams) error
}

var _ Querier = (*Queries)(nil)
