// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	//*********************************
	InsertMCPServerImage(ctx context.Context, arg InsertMCPServerImageParams) error
	InsertMCPServerInstance(ctx context.Context, arg InsertMCPServerInstanceParams) error
	//*********************************
	InsertOauthProvider(ctx context.Context, arg InsertOauthProviderParams) error
	InsertOauthToken(ctx context.Context, arg InsertOauthTokenParams) error
}

var _ Querier = (*Queries)(nil)
